/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import apache.commons.math3.*;

public class App {
    public String getGreeting() {
        return "Hello world!";
    }

    public static void main(String[] args) {



        System.out.println(new App().getGreeting());
    }
}
